site_name: Deep Learning Course with AI
site_description: 'An example of an intelligent textbook for teaching deep learning. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/deep-learning-course/'
repo_url: 'https://github.com/dmccreary/deep-learning-course'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About: about.md
  - Course Description: course-description.md
  - Chapters:
    - Introduction: chapters/index.md
    - Activation Functions: chapters/activation-functions.md
    - Model Parameters: chapters/counting-model-parameters/index.md
  - Labs:
    - Introduction: labs/index.md
    - MNIST: labs/mnist/index.md
    - Counting Tokens Per Second: labs/calculating-tokens-per-second.md
  - Prompts:
    - Intro: prompts/index.md
    - Course Description: prompts/02-bloom-taxonomy-description.md
    - Concept Enumeration: prompts/03-concept-enumeration.md
    - Concept Dependencies: prompts/04-concept-dependencies.md
    - Concept Taxonomy: prompts/05-concept-taxonomy.md
    - Glossary of Terms: prompts/06-glossary-of-terms.md
    - Equations: prompts/07-equations.md
    - Word Cloud: prompts/08-word-cloud.md
    - Suggested Simulations: prompts/09-suggested-simulations.md
    - TensorFlow Playground: prompts/11-tensorflow-playground.md
    - Activation Functions: prompts/10-activation-functions.md
    - Timeline: prompts/12-timeline.md
  - MicroSims:
    - Intro: sims/index.md
    - Learning Graph: sims/learning-graph/index.md
    - Wordcloud: sims/wordcloud/index.md
    - Model Parameter Count: sims/param-count/index.md
    - Sliding Window: sims/sliding-window/index.md
    - Timeline: sims/timeline/index.md
    - Templates: sims/templates/index.md
  - Checklist: checklist.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - Feedback: feedback.md
  - License: license.md
  - References: references.md
  - Contact: contact.md
 
# Dan's MicroSite Standards from here down

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: custom
    accent: 'gold'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
  # enable LaTeX extensions
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX